services:
  - type: web
    name: telegram-bot-webhook
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: <ใส่ token bot ของคุณ>
      - key: BASE_URL
        value: https://telegram-bot-webhook.onrender.com
